### PR TITLE
WIP: uncaught exception in decode when fed with non utf8 data

### PR DESCRIPTION
**Pull request by msgpeek**
To reproduce: 
```bash
 deen -v --decode base64 --data asdf | deen -v --decode url -
Traceback (most recent call last):
  File "/usr/bin/deen", line 11, in <module>
    load_entry_point('deen==0.9.1', 'console_scripts', 'deen')()
  File "/usr/lib/python3.6/site-packages/deen/main.py", line 112, in main
    decoded = transformer.decode(args.decode, content)
  File "/usr/lib/python3.6/site-packages/deen/transformers/core.py", line 130, in decode
    output = urllibparse.unquote_plus(data.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 1: invalid continuation byte
```

Wouldn't it be better to just catch everything generically? I know it's bad practice, but in your case you do not react to any of the exceptions in a specific way. To catch all garbage that can go wrong with encoding seems an impossible task, or at least not worth while.

### CODE REVIEW

**Comment by msgpeek** [comment]
The same issue applies to encoding methods. Do you want me to implement the error_handling similar to decode-variants, i.e. introducing an error-var and return a tuple? (I'll squash later).

My unit-test foo is rusty, why both of the following succeed?
```python
    data_str = 'http%3A%2F%2Fasdf.com'
    self.assertRaises(TypeError, functools.partial(
        self._transformer.decode, 'url', data_str),
        'Unexpected exception raised')

   data_str = b'j\xc7_'    
   self.assertRaises(TypeError, functools.partial(
        self._transformer.decode, 'url', data_str),
        'Unexpected exception raised')
```

**Comment by takeshixx** [comment]
Good catch, thanks for the PR. Catching all exceptions could be a good idea. I think the best solution would be to try to implement a generic error message (e.g. "cannot decode") or just ignore the error and return the input without any changes. Then, a second catch for all other exceptions could just log the errors.

**Comment by takeshixx** [comment]
I'm not sure if it makes sense to implement a similar error handling for encode(). The used library functions should generally return the input or succeed without any errors. The only thing I see here that could happen is if the functions except strings or bytes. Most should be fine with bytes, but e.g. ROT13 expects strings.

Do you happen to know a case where the encoding could fail in the current implementation?

For the test cases: I'm not really sure, but I would assume that the first case should fail with an assertion error. On which Python version did you run those tests?

**Comment by msgpeek** [comment]
> Do you happen to know a case where the encoding could fail in the current implementation?

Everywhere where you use ``data.decode()``. So, deen's ``encode(self, enc, data):`` method will fail on non-utf8 input for enc={url, html, rot13, utf8, utf16}. The latter is ironic, but fails with ``UnicodeDecodeError: 'utf-8' codec can't ..``, too. The reason is the ``data.decode()`` before encoding happens. To do try/except is not enough here.

> or just ignore the error and return the input without any changes

I find the current solution pretty good. Imo, a notification about wrong input makes sense. When then user sees the output, she gets a good understanding about what's wrong with the input.

 My point targets the code only, where you handle them generically, but catch them specifically, e.g., TypeError or binascii.Error, both result in same action. 

> For the test cases: I'm not really sure, but I would assume that the first case should fail with an assertion error. On which Python version did you run those tests?

The same as you, v3.6.2 :)

**Comment by takeshixx** [comment]
Yes encode() will fail for non-utf8 input, because it has been designed like this. At some point there has been a major change in deen which changed the data attribute of the transfomer to bytearray. The idea was to enforce that the raw input data will always be forced to bytes. That's why encode() and decode() have been implemented to always expect bytes, e.g. that's why this assertion is the first line in encode():

`assert isinstance(data, (bytearray, bytes))
`
So if you supply non-bytes data to encode() it should always fail with an assertion error (at least that's the intention).

**Pull request merged**
